# AFL team line-up cache

`lineups_latest.json` is generated by the **AFL Team Line-ups** GitHub Action.

The collector opens the official AFL Team Line-ups page in Chromium, captures the
page's authenticated roster responses, validates the full round and only then
replaces the last-known-good file. Failed runs leave the previous file untouched
and upload a screenshot, rendered HTML and response diagnostics as workflow
artifacts.
